# Generated by Django 5.0.7 on 2024-08-18 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenzzinssatz', models.DecimalField(decimal_places=3, help_text='Wert zwischen 0 und 100 mit maximal drei Nachkommastellen', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Referenzzinssatz')),
            ],
        ),
    ]
