# Generated by Django 5.0.7 on 2024-08-25 15:56

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliokonfigurator', '0002_historicalreferenzzinssatz_qualitaetsfaktor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenzzinssatz', models.DecimalField(decimal_places=2, help_text='Referenzzinssatz in Prozent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kapitalisierungsfaktor', models.DecimalField(decimal_places=2, help_text='Kapitalisierungsfaktor in Prozent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Globale Einstellungen',
                'verbose_name_plural': 'Globale Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGlobalSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('referenzzinssatz', models.DecimalField(decimal_places=2, help_text='Referenzzinssatz in Prozent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('kapitalisierungsfaktor', models.DecimalField(decimal_places=2, help_text='Kapitalisierungsfaktor in Prozent', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Globale Einstellungen',
                'verbose_name_plural': 'historical Globale Einstellungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalreferenzzinssatz',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Referenzzinssatz',
        ),
        migrations.DeleteModel(
            name='HistoricalReferenzzinssatz',
        ),
    ]
