# Generated by Django 5.0.7 on 2024-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliokonfigurator', '0003_globalsettings_historicalglobalsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitaetsfaktorKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Qualitätsfaktor-Kategorie',
                'verbose_name_plural': 'Qualitätsfaktor-Kategorien',
            },
        ),
    ]
