# Generated by Django 5.0.7 on 2024-08-25 16:42

import django.db.models.deletion
import portfoliokonfigurator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliokonfigurator', '0004_qualitaetsfaktorkategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitaetsfaktor',
            name='kategorie',
            field=models.ForeignKey(default=portfoliokonfigurator.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, related_name='qualitaetsfaktoren', to='portfoliokonfigurator.qualitaetsfaktorkategorie'),
        ),
        migrations.AlterUniqueTogether(
            name='qualitaetsfaktor',
            unique_together={('kategorie', 'name')},
        ),
    ]
