# Generated by Django 5.0.7 on 2024-08-08 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siedlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(help_text='Maximal 5 Zeichen', max_length=5, verbose_name='Interne ID')),
                ('bezeichnung', models.CharField(help_text='Maximal 120 Zeichen', max_length=120, verbose_name='Bezeichnung')),
                ('anlagewert', models.IntegerField(help_text='Auch bekannt als Anlagekosten oder Investitionswert. Erfassen ohne Nachkommastellen.', verbose_name='Anlagewert')),
                ('versicherungswert', models.IntegerField(help_text='Versicherungswert gem. GVZ Police. Erfassen ohne Nachkommastellen.', verbose_name='GVZ-Wert')),
                ('baurechtszins', models.IntegerField(verbose_name='Baurechtszins')),
                ('betriebsquote_zuschlag', models.DecimalField(blank=True, decimal_places=2, help_text='Erfasse einen Wert zwischen 0 und 100 mit maximal zwei Nachkommastellen', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Betriebsquote Zuschlag')),
            ],
        ),
    ]
