# Generated by Django 5.0.7 on 2024-08-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siedlung',
            name='baurechtszins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baurechtszins'),
        ),
        migrations.AlterField(
            model_name='siedlung',
            name='internal_id',
            field=models.CharField(help_text='Maximal 5 Zeichen', max_length=5, unique=True, verbose_name='Interne ID'),
        ),
    ]
