# Generated by Django 5.0.7 on 2024-08-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0002_alter_siedlung_baurechtszins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siedlung',
            options={'ordering': ['-internal_id']},
        ),
    ]
