# Generated by Django 5.0.7 on 2024-08-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0004_alter_siedlung_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_oid', models.CharField(help_text='Maximal 10 Zeichen', max_length=10, unique=True, verbose_name='OID')),
                ('siedlung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siedlungsmanager.siedlung')),
            ],
        ),
    ]
