# Generated by Django 5.0.7 on 2024-08-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0005_objekt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objekt',
            options={'ordering': ['internal_oid']},
        ),
    ]
