# Generated by Django 5.0.7 on 2024-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0006_alter_objekt_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='bereich',
            field=models.CharField(choices=[('B2', 'B2'), ('B3', 'B3'), ('GZ', 'GZ')], default='B2', max_length=2),
        ),
        migrations.AddField(
            model_name='objekt',
            name='bezeichnung',
            field=models.CharField(default='Wohnung', help_text='Maximal 120 Zeichen', max_length=120, verbose_name='Bezeichnung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objekt',
            name='punkte',
            field=models.DecimalField(choices=[(5.5, '5.5 Punkte - 1.5 Zimmer'), (6, '6 Punkte - 2.0 Zimmer'), (6.5, '6.5 Punkte - 2.5 Zimmer'), (7.5, '7.5 Punkte - 3.0 Zimmer'), (8.0, '8.0 Punkte - 3.5 Zimmer'), (9.0, '9.0 Punkte - 4.0 Zimmer'), (9.5, '10.0 Punkte - 4.5 Zimmer'), (10.5, '10.5 Punkte - 5.0 Zimmer'), (11.5, '11.5 Punkte - 5.5 Zimmer'), (12.5, '12.0 Punkte - 6.0 Zimmer')], decimal_places=1, default=8.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='siedlung',
            name='anlagewert',
            field=models.PositiveIntegerField(help_text='Auch bekannt als Anlagekosten oder Investitionswert. Erfassen ohne Nachkommastellen.', verbose_name='Anlagewert'),
        ),
        migrations.AlterField(
            model_name='siedlung',
            name='baurechtszins',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Baurechtszins'),
        ),
        migrations.AlterField(
            model_name='siedlung',
            name='versicherungswert',
            field=models.PositiveIntegerField(help_text='Versicherungswert gem. GVZ Police. Erfassen ohne Nachkommastellen.', verbose_name='GVZ-Wert'),
        ),
    ]
