# Generated by Django 5.0.7 on 2024-08-09 19:46

import django.core.validators
import siedlungsmanager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0007_objekt_bereich_objekt_bezeichnung_objekt_punkte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objekt',
            name='aktuelle_miete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), siedlungsmanager.validators.validate_last_decimal_for_currency]),
        ),
    ]
