# Generated by Django 5.0.7 on 2024-08-13 15:34

import django.core.validators
import siedlungsmanager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0009_alter_siedlung_baurechtszins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekt',
            name='aktuelle_miete',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), siedlungsmanager.validators.validate_last_decimal_for_currency], verbose_name='Aktuelle Miete'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='bereich',
            field=models.CharField(choices=[('B2', 'B2'), ('B3', 'B3'), ('GZ', 'GZ')], default='B2', max_length=2, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='objekt',
            name='punkte',
            field=models.DecimalField(choices=[(5.5, '5.5 Punkte - 1.5 Zimmer'), (6, '6 Punkte - 2.0 Zimmer'), (6.5, '6.5 Punkte - 2.5 Zimmer'), (7.5, '7.5 Punkte - 3.0 Zimmer'), (8.0, '8.0 Punkte - 3.5 Zimmer'), (9.0, '9.0 Punkte - 4.0 Zimmer'), (9.5, '10.0 Punkte - 4.5 Zimmer'), (10.5, '10.5 Punkte - 5.0 Zimmer'), (11.5, '11.5 Punkte - 5.5 Zimmer'), (12.5, '12.0 Punkte - 6.0 Zimmer')], decimal_places=1, default=8.0, max_digits=3, verbose_name='Punkte'),
        ),
    ]
