# Generated by Django 5.0.7 on 2024-08-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0010_alter_objekt_aktuelle_miete_alter_objekt_bereich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekt',
            name='siedlung',
            field=models.ForeignKey(help_text='Achtung: ordnet das Objekt der ausgewählten Siedlung zu!', on_delete=django.db.models.deletion.CASCADE, to='siedlungsmanager.siedlung'),
        ),
    ]
