# Generated by Django 5.0.7 on 2024-08-18 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siedlungsmanager', '0011_alter_objekt_siedlung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siedlung',
            name='betriebsquote_zuschlag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wert zwischen 0 und 100 mit maximal zwei Nachkommastellen', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Betriebsquote Zuschlag'),
        ),
    ]
